CREATE TABLE
  users (
    id BIGSERIAL PRIMARY KEY,
    short_name TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL
  );

CREATE TABLE
  notes (
    id BIGSERIAL PRIMARY KEY,
    author_id BIGINT NOT NULL,
    title TEXT NOT NULL UNIQUE,
    text TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notes_author_id_foreign FOREIGN KEY (author_id) REFERENCES users (id) ON DELETE CASCADE
  );
